#include <string.h>
#include <string>
#include <sys/socket.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <vector>
#include <semaphore.h>
#include <pthread.h>
#include <filesystem>
#include <fstream>
#include <iostrem>
#include "globals.h"